site_name: Neoflow Documentation
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  favicon: images/neoflow-logo.svg
  logo: images/neoflow-logo.svg
  font: Roboto
  palette:
    primary: md-primary-fg-color
  theme:
  features:
    - navigation.tracking
    - toc.follow
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
        permalink: "#"
nav:
    - Introduction: index.md
    - Platform Overview: platform-overview.md
    - Security and Data Privacy: security-and-data-privacy.md
    - Data Governance: data-governance.md
    - Key Concepts: key-concepts.md
    - API User Guide:  api-user-guide.md
copyright: Copyright &copy; Neoflow. All rights reserved.